name: CI Workflow

on:
  push: {}
  workflow_dispatch: {}

env:
  REGISTRY: git.luzifer.io
  IMAGE: registry/mimap

jobs:
  test:
    runs-on: forgejo

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false

      - run: make lint test


  docker-publish:
    needs: test

    defaults:
      run:
        shell: bash

    runs-on: forgejo

    steps:
      - uses: luzifer/actions/docker-publish@develop
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          push: ${{ github.ref == 'refs/heads/master' }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
